"""empty message

Revision ID: ff24af92c366
Revises: 615b7d080a7e
Create Date: 2018-04-23 16:07:01.953082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff24af92c366'
down_revision = '615b7d080a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('asked_by_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'asked_by_id')
    # ### end Alembic commands ###
