"""empty message

Revision ID: 4c4bc6a6d559
Revises: 
Create Date: 2018-04-13 17:08:47.735300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4bc6a6d559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('protein', sa.String(length=30), nullable=True),
    sa.Column('carbohydrates', sa.String(length=30), nullable=True),
    sa.Column('fat', sa.String(length=30), nullable=True),
    sa.Column('calories', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_date',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('log_date_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('log_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_date')
    op.drop_table('food_date')
    op.drop_table('food')
    # ### end Alembic commands ###
